version: "{build}-{branch}"

branches:
  except:
    - gh-pages

init:
  - ps: $PSVersionTable.keys |% {"$_ $($PSVersionTable[$_])"}
  - ps: (get-psprovider 'FileSystem').Home = $(pwd)
  - ps: "if($env:APPVEYOR_CHOCO_PESTER_OPTIONS -ne $null) { write-host -f yellow 'NOTE: customized `pester` installation is being used' }"
  - ps: choco install -y pester $env:APPVEYOR_CHOCO_PESTER_OPTIONS

build: off

test_script:
  - ps: $env:TEST_ALL = $true
  - ps: powershell -c "invoke-pester -quiet -script .\test -excludetag disabled,appveyor.disabled -outputfile '.\test\#TestResults.xml' -outputformat NUnitXML" | out-null
  - ps: $env:failedcount = $([xml]$(get-content '.\test\#TestResults.xml')).'test-results'.'failures'
  - ps: .\test\bin\summarize-results.ps1 '.\test\#TestResults.xml'
  - ps: (new-object net.webclient).uploadfile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (resolve-path '.\test\#TestResults.xml'))
  - ps: if($env:failedcount -gt 0) { exit $env:failedcount }
